import { formatDateTimeStamp } from "@/lib/utils"
export const columnsAttendance = [

  {
    title: "Date",
    dataIndex: "work_date",
    key: "work_date",
    width: 150,
    align: 'center',
    sorter: (a, b) => a.work_date.localeCompare(b.work_date),
  },
  {
    title: "Department",
    dataIndex: "department",
    key: "department",
    width: 160,
    align: 'center',
    sorter: (a, b) => a.department.localeCompare(b.department),
  },
  {
    title: "Employee ID",
    dataIndex: "user_id",
    key: "user_id",
    width: 160,
    align: 'center',
    sorter: (a, b) => a.user_id.localeCompare(b.user_id),
  },
  {
    title: "Staff Name",
    dataIndex: "name",
    key: "name",
    width: 160,
    align: 'center',
    sorter: (a, b) => a.name.localeCompare(b.name),
  },
  {
    title: "Check In",
    dataIndex: "check_in",
    key: "check_in",
    width: 160,
    align: 'center',
    sorter: (a, b) => a.check_in.localeCompare(b.check_in),
  },
  {
    title: "Break In",
    dataIndex: "email",
    key: "email",
    width: 180,
    align: 'center',
    sorter: (a, b) => a.email.localeCompare(b.email),
  },
  {
    title: "Break Out",
    dataIndex: "email",
    key: "email",
    width: 180,
    align: 'center',
    sorter: (a, b) => a.email.localeCompare(b.email),
  },
  {
    title: "Check Out",
    dataIndex: "check_out",
    key: "check_out",
    width: 160,
    align: 'center',
    sorter: (a, b) => a.check_out.localeCompare(b.check_out),
  },
  {
    title: "Total",
    dataIndex: "email",
    key: "email",
    width: 180,
    align: 'center',
    sorter: (a, b) => a.email.localeCompare(b.email),
  },
  {
    title: "Type",
    dataIndex: "email",
    key: "email",
    width: 180,
    align: 'center',
    sorter: (a, b) => a.email.localeCompare(b.email),
  },
  {
    title: "Employee Note",
    dataIndex: "email",
    key: "email",
    width: 180,
    align: 'center',
    sorter: (a, b) => a.email.localeCompare(b.email),
  },
  {
    title: "Manager Note",
    dataIndex: "email",
    key: "email",
    width: 180,
    align: 'center',
    sorter: (a, b) => a.email.localeCompare(b.email),
  },
];